### ISSUE TITLE
likely bug in local chord computation

### ISSUE THREAD

**Issue by jsaldia** [montagdude/weissinger#3]
It seems there is a bug in the local chord computation in line 72 of weissenger.py
c[i]     = wing.root + (wing.tip-wing.root)*y[i] #local chord
it should be replaced to 
c[i]     = wing.root + (wing.tip-wing.root)*np.abs(y[i]) #local chord

**Comment by montagdude** [comment]
Yes, you're right. Interestingly it doesn't make a big difference in the results for the test case.

Fixed in 9722959.
